development:
  adapter: postgresql
  encoding: unicode
  database: wwwha_development
  pool: 5
  username: mariamercedesmartinez
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wwwha_test
  pool: 5
  username: mariamercedesmartinez
  password:
