# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

[
  "Repression",
  "Kanye West",
  "White privilege",
  "Ice dancing",
  "Crystal meth",
  "Dropping a chandelier on your enemies and riding the rope up",
  "William Shatner",
  "Grandma",
  "The Amish",
  "The Rapture",
  "Old-people smell",
  "A mime having a stroke",
  "The hustle",
  "Altar boys",
  "A bag of magic beans",
  "A death ray",
  "Farting and walking away",
  "Third base",
  "Puppies",
  "Count Chocula",
  "Soiling oneself",
  "Being on fire",
  "Parting the Red Sea",
  "Puberty",
  "Obesity",
  "The Dance of the Sugar Plum Fairy",
  "Sniffing glue",
  "Darth Vader",
  "Sarah Palin",
  "Peeing a little bit",
  "Homeless people",
  "A drive-by shooting",
  "Friction",
  "Serfdom",
  "Being fabulous",
  "Vigorous jazz hands",
  "A falcon with a cap on its head",
  "Exactly what you'd expect",
  "Gandhi",
  "A fetus",
  "Breaking out into song and dance",
  "All-you-can-eat shrimp for $4.99",
  "Police brutality",
  "Smallpox blankets",
  "Teenage pregnancy",
  "Poorly-timed Holocaust jokes",
  "Daddy issues",
  "Fancy Feast",
  "The terrorists",
  "Bingeing and purging",
  "German dungeon porn",
  "Children on leashes",
  "Passive-aggressive Post-it notes",
  "Spectacular abs",
  "Euphoria by Calvin Klein",
  "Morgan Freeman's voice",
  "Sean Connery",
  "Authetic Mexican cuisine",
  "Crippling debt",
  "Her Royal Highness Queen Elizabeth II",
  "Judge Judy",
  "A tiny horse",
  "Pretending to care",
  "The Chinese gymnastics team",
  "Laying an egg",
  "Sexting",
  "Science",
  "God",
  "Former President George W. Bush",
  "Getting drunk on mouthwash",
  "Alcoholism",
  "Civilian casualties",
  "Kids with ass cancer",
  "Incredibly poor and hungry children",
  "Goats eating cans",
  "An Oedipus complex",
  "Assless chaps",
  "Seppuku",
  "Penis envy",
  "'Tweeting'",
  "Wifely duties",
  "Concealing a boner",
  "Cybernetic enhancement",
  "Keanu Reeves",
  "Saxphone solos",
  "Taking off your shirt",
  "Prancing",
  "Santa Claus",
  "Keg stands",
  "College",
  "Bees?",
  "Britney Spears at 55",
  "The Blood of Christ",
  "The KKK",
  "The Donald Trump Seal of Approval",
  "The profoundly handicapped",
  "The miracle of childbirth",
  "Whipping it out",
  "Another goddamn Hobbit movie",
  "RoboCop",
  "The folly of man",
  "My sex life",
  "A disappointing birthday party",
  "Re-gifting",
  "Heartwarming orphans",
  "Surprise sex!",
  "The invisible hand",
  "A moment of silence",
  "My relationship status",
  "Global warming",
  "The violation of our most basic human rights",
  "Sweet, sweet vengeance",
  "A balanced breakfast",
  "Consultants",
  "Men",
  "Intelligent design",
  "Charisma",
  "Child abuse",
  "Vikings",
  "Republicans",
  "Dying",
  "Dental dams",
  "Mutually assured destruction",
  "The inevitable death of the universe",
  "Sexy pillow fights",
  "Too much hair gel",
  "Catapults",
  "A clandestine butt scratch",
  "Chainsaws for hands",
  "Poor people",
  "Friendly fire",
  "Cuddling",
  "A stinky poo",
  "Hot people",
  "Team-building exercises",
  "Getting naked and watching Nickelodeon",
  "Leaving an awkward voicemail",
  "A foul mouth",
  "Cheating in the Special Olympics",
  "Not giving a shit about the Third World",
  "Domino's Oreo Dessert Pizza",
  "Natural selection",
  "Spontaneous human combustion",
  "Hormone injections",
  "Horse meat",
  "Booby-trapping the house to foil burglars",
  "Estrogen",
  "The milkman",
  "Stranger danger",
  "Teaching a robot to love",
  "AXE Body Spray",
  "Actually taking candy from a baby",
  "A monkey smoking a cigar",
  "Dick Cheney",
  "Licking things to claim them as your own",
  "Chivalry",
  "BATMAN!!",
  "Multiple stab wounds",
  "Panda sex",
  "A zesty breakfast burrito",
  "Stephen Hawking talking dirty",
  "Guys who don't call",
  "A sausage festival",
  "Natural male enhancement",
  "Lady Gaga",
  "Object permanence",
  "The Virginia Tech Massacre",
  "Nocturnal emissions",
  "An icepick lobotomy",
  "Masturbation",
  "Doing the right thing",
  "The chronic",
  "Flightless birds",
  "Public ridicule",
  "Nazis",
  "General Assembly's WDI teachers"
  "A sea of troubles",
  "Free samples",
  "Horrifing laser removal accidents",
  "Making a pouty face",
  "Wiping her butt",
  "Being a motherfucking sorcerer",
  "Centaurs",
  "A Super Soaker full of cat pee",
  "A depressed zoo lion",
  "Skeletor",
  "A hot mess",
  "Lance Armstrong's missing testacle",
  "The American Dream",
  "Oompa-Loopas",
  "Riding off into the sunset",
  "The Underground Railroad",
  "Soup that is too hot",
  "A brain tumor",
  "Exchanging pleasantries",
  "Waiting 'til marriage",
  "Hope",
  "Sexual tension",
  "Copping a feel",
  "A stray pube",
  "Getting really high",
  "A Gypsy curse",
  "Goblins",
  "Vehicular manslaughter",
  "Cards Against Humanity",
  "Kamikaze Pilots",
  "My soul",
  "Friends who eat all the snacks"
  "Waterboarding",
  "Flesh-eating bacteria",
  "Me time",
  "Genghis Khan",
  "Sunshine and rainbows",
  "A room full of corpses",
  "Leprosy",
  "The heart of a child",
  "A murder most foul",
  "Giving 110%",
  "Explosions",
  "Wearing underwear inside-out to avoid doing laundry",
  "Inappropriate yodeling",
  "An asymmetric face lift",
  "A gentle caress of the inner thigh",
  "Scalping",
  "The fobidden fruit",
  "Being Rich",
  "Eating the last known Bison",
  "The South",
  "Five-Dollar Footlongs",
  "Amputees",
  "Seduction",
  "Women in yogurt commercials",
  "Land mines",
  "Waking up half-naked in a Denny's parking lot"
  "Dead parents",
  "Poor life choices",
  "A cooler full of organs",
  "Child beauty pageants",
  "Full frontal nudity",
  "The Tempur-Pedic Swedish Sleep System",
  "Harry Potter erotica",
  "A really cool hat",
  "A thermonuclear detonation",
  "A time travel paradox",
  "Being mean to children",
  "Winking at old people",
  "My collection of high-tech dog toys",
  "Dead babies",
  "A can of whoop-ass",
  "Drinking alone",
  "World Peace",
  "The true meaning of Christmas",
  "The World of Warcraft",
  "A lifetime of sadness",
  "Bill Nye the Science Guy",
  "My inner demons",
  "An honest cop with nothing left to lose",
  "A good sniff",
  "Customer service representatives",
  "My genitals"  
].each do |card_text|
  WhiteCard.create(text: card_text)
end